### ISSUE TITLE
windows上状态栏显示不对

### ISSUE THREAD

**Issue by CapZhang** [KiteAB/.emacs.d#2]
您好，我在B站看到了您的配置，下载下来后发现状态栏不对，是一个很亮的颜色，要hover上去才有信息显示出来，请教这个要怎么处理呢
windows10，emacs 27.1
![image](https://user-images.githubusercontent.com/19522615/96711738-9f335980-13d0-11eb-9384-0208abcdd99c.png)

**Comment by KiteAB** [comment]
> 您好，我在B站看到了您的配置，下载下来后发现状态栏不对，是一个很亮的颜色，要hover上去才有信息显示出来，请教这个要怎么处理呢
> windows10，emacs 27.1
> ![image](https://user-images.githubusercontent.com/19522615/96711738-9f335980-13d0-11eb-9384-0208abcdd99c.png)

你先把所有错误都处理完再试试

**Comment by KiteAB** [comment]
@CapZhang Issue will close 2 days later, Please report current issue situation!

**Comment by CapZhang** [comment]
我试验了几次，发现两个问题
1. 在init-basic.el里，  (setq locale-coding-system   'utf-8)   会导致awesome-tray  的“date” 在我的windows上是乱码
2. 在init-ui.el里，Circadian 插件的使用会导致 awesome-tray  的modeline高度设置失效，变成原来的高度，但是最佳体验是一条线


![image](https://user-images.githubusercontent.com/19522615/97246024-51d34400-1837-11eb-952d-3f5bb6034018.png)

**Comment by KiteAB** [comment]
> 我试验了几次，发现两个问题
> 
> 1. 在init-basic.el里，  (setq locale-coding-system   'utf-8)   会导致awesome-tray  的“date” 在我的windows上输出的中文周几显示为乱码
> 2. 在init-ui.el里，Circadian 插件的使用会导致 awesome-tray  的modeline高度设置失效，变成原来的高度，但是最佳体验是一条线
> 
> ![image](https://user-images.githubusercontent.com/19522615/97246024-51d34400-1837-11eb-952d-3f5bb6034018.png)

那也就证明这份配置只在linux使用更佳   这些东西你可能更适合在linux下跑或者问插件作者

**Comment by KiteAB** [comment]
> 我试验了几次，发现两个问题
> 
> 1. 在init-basic.el里，  (setq locale-coding-system   'utf-8)   会导致awesome-tray  的“date” 在我的windows上输出的中文周几显示为乱码
> 2. 在init-ui.el里，Circadian 插件的使用会导致 awesome-tray  的modeline高度设置失效，变成原来的高度，但是最佳体验是一条线
> 
> ![image](https://user-images.githubusercontent.com/19522615/97246024-51d34400-1837-11eb-952d-3f5bb6034018.png)

第一个问题是awesome-tray实现的时候就是针对于linux的  这没办法
第二个问题  把图截全并尽量清晰

**Comment by KiteAB** [comment]
@CapZhang Issue will close 2 days later, Please report current issue situation!

**Comment by KiteAB** [comment]
呃   实在这样的话utf-8设置可以去掉  然后我不用circadian了   如果没有问题了的话就close吧

**Comment by CapZhang** [comment]
哦哦不好意思，utf-8去掉后可以正常显示了，高度失效的问题是因为有些显示在modeline里的信息设置高度的时候倔强的按照原来的高度显示，比如buffer name、clock in 这两个，后来再一次瞎整后莫名其妙的解决了这两个问题

不好意思github用的不熟，我close了。。
